# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Release App

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        run: gh release create "${{  github.ref_name }}" --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    needs: release
    strategy:
      matrix:
        GOOS: [darwin, linux]
        GOARCH: [amd64, arm64]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Build
        run: go build -v ./... -o "keysync.${{ matrix.GOOS }}-${{ matrix.GOARCH }}"
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}

      - name: Test
        run: go test -v ./...
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}

      - name: Upload asset
        run: gh release upload "${{  github.ref_name }}" "./keysync.${{ matrix.GOOS }}-${{ matrix.GOARCH }}"
        env:
          GH_TOKEN: ${{ github.token }}
