# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test & Release

on:
  push:
    pull_request:
    branches-ignore:
      - 'dependabot/**'
    tags:
      - '*'

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Create Release
        run: gh release create "${{  github.ref_name }}" --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        GOOS: [darwin, linux]
        GOARCH: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Restore Go modules cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('go.mod') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v ./... -o "keysync.${{ matrix.GOOS }}-${{ matrix.GOARCH }}"
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}

      - name: Test
        run: go test -v ./...
        env:
          GOOS: ${{ matrix.GOOS }}
          GOARCH: ${{ matrix.GOARCH }}

  publish:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    needs: build
    steps:
      - name: Upload asset
        run: gh release upload "${{  github.ref_name }}" "./keysync.${{ matrix.GOOS }}-${{ matrix.GOARCH }}"
        env:
          GH_TOKEN: ${{ github.token }}
